### ISSUE TITLE
Gold ore making and coal bag issues

### ISSUE THREAD

**Issue by Kas3m** [Toofifty/easy-blastfurnace#20]
Hello, I'm having an issue with the plugin whenever making bars of any kind that requires coal and having the coal bag full in inventory it toggles into empty and points to the bank skipping the empty coal bag in put ore on conveyor part.
second issue is making gold bars with gloves goldsmith guantlets on and ice gloves in inventory when I put the gold ores on the conveyor it imediatly asks to wear the ice gloves it always was pointing to the tile next to bar dispenser first then ice gloves then the bar dispenser itself to get the gold bars now it skips pointing to the tile.
thank you so much for your great plugin and your efforts

**Comment by Kas3m** [comment]
sorry misclicked close button

**Comment by hugocowan** [comment]
Hey @Kas3m, so the first issue is a known bug which has been fixed, the new version is waiting to be merged into Runelite's plugin hub.

The second issue about equipping the ice gloves - that's fair, I'll look to fix that. It's due to a change I made, now I think about it, I likely shouldn't have made it.

**Comment by Kas3m** [comment]
thank you so much for all your efforts man
