### ISSUE TITLE
option for tick perfect gold bars

### ISSUE THREAD

**Issue by Jerrk** [Toofifty/easy-blastfurnace#26]
like in this video here: https://www.youtube.com/watch?v=XIH6Y6_3YKI

Where you always keep 27 gold bars in the furnace and withdraw them before the current batch has finished smelting.

would be a nice option to include

**Comment by hugocowan** [comment]
Hey there @Jerrk. I actually did read this and have a think about it. A lot of what's happening in this video is using the Screen Markers plugin to mark locations of their deposit inventory button and the gold ore in their bank. This is handled by a different plugin, not easy-blastfurnace.

Saying that, there is an option in the config to highlight the deposit inventory button instead of the gold bars. The option is called "Use deposit inventory button". That will get you part of the way there.

**Comment by Jerrk** [comment]
I'm specifically talking about the actions to take while making gold bars with this method does not line up with the overlays created by this plugin.

Specifically:
with 27 bars in the dispenser and 27 ore in your inventory you're supposed to wear your ice gloves.
the plugin prompts you to put on your goldsmith gauntlets.
![image](https://user-images.githubusercontent.com/49324581/226608068-35e92e06-0967-47e7-a9f3-6c4725b07753.png)

after depositing 27 ores you're supposed to wear your ice gloves, click on the tile west of the dispenser, and the tick you reach that tile you click on the dispenser. 
The plugin only highlights the dispenser the entire time
![image](https://user-images.githubusercontent.com/49324581/226608319-c63776c9-52df-470c-9574-63a480584dcf.png)

After withdrawing 27 bars from the dispenser while wearing ice gloves, you're supposed to put on goldsmith gauntlets on the same tick as the bars fill your inventory.
the plugin highlights the bank as soon as the bars enter your inventory while still wearing the ice gloves
![image](https://user-images.githubusercontent.com/49324581/226609327-b134b22e-d151-43bc-94c0-3f4600278abb.png)


After wearing the goldsmith gauntlets and getting the xp drop you're supposed to use the bank
The plugin prompts you to put your ice gloves back on but then it highlights the dispenser again.

**Comment by hugocowan** [comment]
@Jerrk Hey, it's been a while. I'm submitting a change to add the tick perfect gold method now.
